version: "3.7"

services:
  digital-catalogue:
    build: .
    container_name: digital-catalogue
    restart: unless-stopped
    command: ./docker-entrypoint.sh
    environment:
      - DEBUG=FALSE
      - PYTHONUNBUFFERED=1
    ports:
      - "7279:7279"
